# Generated by Django 4.1.1 on 2022-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                (
                    "designation",
                    models.CharField(
                        choices=[("student", "STUDENT"), ("teacher", "TEACHER")],
                        default="student",
                        max_length=7,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Profile",},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("hours_watched", models.FloatField(max_length=100)),
            ],
            options={"verbose_name_plural": "Students",},
        ),
    ]
